settings:
  min-players: 1 # Minimum amount of players to send a broadcast
  delay: 10 # Delay in seconds to start announcement after a reload
  period: 300 # Period in seconds to send announcements to players

announcements:
  '1':
    chat:
      - ''
      - ' <aqua><b>Hello</b></aqua> <dark_gray>|</dark_gray> <white>Server Information'
      - ' <dark_gray><b>></b></dark_gray> <gray>Be sure to check-out our store <aqua><u>store.leo.cx</u></aqua>!'
      - ''
    action-bar: '<dark_aqua>[<aqua><b>Announcement</b></aqua>]</dark_aqua> <gray>Be sure to check-out our store <aqua><u>store.leo.cx</u></aqua>!'
    title:
      header: '<aqua><b>ANNOUNCEMENT</b></aqua>'
      subtitle: '<gray>Be sure to check-out our store <aqua><underline>store.leo.cx</underline></aqua>!'
      intervals:
        fade-in: 500
        stay: 3000
        fade-out: 1000