name: announcer
version: "${pluginVersion}"
main: cx.leo.announcer.AnnouncerPlugin
description: "${description}"
authors: [ItsSimplyLeo]
api-version: "${apiVersion}"

commands:
  announcer:
    description: "Main command to handle the announcer plugin"
    permission: "announcer.command.main"